batting_categories = {"Games Played":"GP",
"Games Started":"GS_BAT",
"At Bats":"AB",
"Runs":"R",
"Hits":"H",
"Singles":"1B",
"Doubles":"2B",
"Triples":"3B",
"Home Runs":"HR",
"Runs Batted In":"RBI",
"Sacrifice Hits":"SH",
"Sacrifice Flys":"SF",
"Stolen Bases":"SB",
"Caught Stealing":"CS",
"Walks":"BB",
"Intentional Walks":"IBB",
"Hit By Pitch":"HBP",
"Strikeouts":"K_BAT",
"Ground Into Double Play":"GIDP",
"Total Bases":"TB_Bat",
"Putouts":"PO",
"Assists":"A",
"Errors":"ERR",
"Fielding Percentage":"FIELD",
"Batting Average":"BA",
"On-base Percentage":"OBP",
"Slugging Percentage":"SLG",
"On-base + Slugging Percentage":"OPS",
"Extra Base Hits":"EXBH",
"Net Stolen Bases":"NSB",
"Stolen Base Percentage":"SB_PER",
"Hitting for the Cycle":"CYCLE",
"Plate Appearances":"PA",
"Grand Slam Home Runs":"GSHR",
"Outfield Assists":"OA",
"Double Plays Turned":"DPT",
"Catcher Interference":"CI"}


pitching_categories = {"Pitching Appearances":"PITCH_APP",
"Games Started":"GS_PITCH",
"Innings Pitched":"IP",
"Wins":"W",
"Losses":"L",
"Complete Games":"CG",
"Shutouts":"SO",
"Saves":"SV",
"Outs":"O",
"Hits":"H_PITCH",
"Total Batters Faced":"TBF",
"Runs":"R_PITCH",
"Earned Runs":"ER",
"Home Runs":"HRA",
"Walks":"BBA",
"Intentional Walks":"IBBA",
"Hit Batters":"HB",
"Strikeouts":"K_PITCH",
"Wild Pitches":"WP",
"Balks":"BALK",
"Stolen Bases Allowed":"SBA",
"Batters Grounded Into Double Plays":"GIDPF",
"Save Chances":"SV_CHANCE",
"Holds":"HLD",
"Total Bases Allowed":"TBA",
"Earned Run Average":"ERA",
"(Walks + Hits)/ Innings Pitched":"WHIP",
"Strikeouts per Walk Ratio":"KBB",
"Strikeouts per Nine Innings":"K9",
"Pitch Count":"PC",
"Singles Allowed":"1BA",
"Doubles Allowed":"2BA",
"Triples Allowed":"3BA",
"Relief Wins":"RW",
"Relief Losses":"RL",
"Pickoffs":"POFF",
"Relief Appearances":"RAPP",
"On-base Percentage Against":"OBPA",
"Winning Percentage":"WIN_PER",
"Hits Per Nine Innings":"H9",
"Walks Per Nine Innings":"B9",
"No Hitters":"NH",
"Perfect Games":"PG",
"Save Percentage":"SV_PER",
"Inherited Runners Scored":"IR_SCORE",
"Quality Starts":"QS",
"Blown Saves":"BS",
"Net Saves":"NSV",
"Saves + Holds":"SVH",
"Net Saves and Holds":"NSVH",
"Net Wins":"NW"}


Low_Categories = ["CS","ERR","K_BAT","GIDP","ERA","WHIP","IR_SCORE","BS","B9","H9","OBPA","RL","3BA","2BA","1BA","TBA","BALK","WP","HB","IBBA","BBA","HRA","ER","R_PITCH","H_PITCH","L"]